name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: knowledge-rag
  AZURE_RESOURCE_GROUP: knowledge-rag-rg

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/knowledge-rag:${{ github.sha }}
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/knowledge-rag:latest
          cache-from: type=registry,ref=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/knowledge-rag:latest
          cache-to: type=inline

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/knowledge-rag:${{ github.sha }}

      - name: Update App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "FLASK_ENV",
                "value": "production"
              },
              {
                "name": "LOG_LEVEL",
                "value": "INFO"
              },
              {
                "name": "CACHE_DIR",
                "value": "/home/cache"
              }
            ]

      - name: Azure logout
        run: |
          az logout
