name: CI - Test and Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black safety pip-audit

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check code formatting with black
        run: |
          black --check .

      - name: Security audit with safety
        run: |
          safety check --json || true

      - name: Audit dependencies with pip-audit
        run: |
          pip-audit || true

      - name: Build Docker image
        run: |
          docker build -t knowledge-rag:test .

      - name: Test Docker image
        run: |
          docker run --rm -e GITHUB_TOKEN=test_token knowledge-rag:test python -c "import app; print('Import successful')"
